---
title: "Automating Reproduciblility"
subtitle: "Challenges and what it takes to meet them"
author: "Aaron Peikert, Maximilian S. Ernst, and Andreas M. Brandmaier"
output: pdf_document
---

Computational reproducibility is a building block for transparent and cumulative science.
It enables the originator and other researchers, on other computers and later in time, to reproduce and thus understand how results came about while avoiding various errors that may lead to erroneous reporting of statistical and computational results.
But what does it take to make something reproducible?
Until recently, detailed descriptions of methods and analyses were the primary instrument for ensuring scientific reproducibility.
Such manual description fails to ensure reproduction due to four different reasons that get more likely the more central computational methods are for research.
To meet these challenges, we propose that researchers take advantage of four technological advancements---version control, dynamic document generation, workflow automation, and containerization.
Our workflow enables scientists to achieve a more comprehensive standard that allows anyone to access a digital research repository and reproduce all computational steps from raw data to final report with a single command.
